### ISSUE TITLE
gulp-api-doc crashing when no apiDoc tags found in code

### ISSUE THREAD

**Issue by dnoliver** [SamVerschueren/gulp-api-doc#4]
We use gulp-api-doc to generate API documentation in Javascript/Express code.

When no apiDoc tags are present, the plugin make gulp crash:

```
[10:43:45] Starting 'apidoc'...
info: Nothing to do.
Thu, 06 Apr 2017 13:43:46 GMT uncaughtException: ENOENT: no such file or directory, stat 'C:\Users\dnoliver\AppData\Local\Temp\598eed49-cedc-40e7-b937-5225a477b62c'
Error: ENOENT: no such file or directory, stat 'C:\Users\dnoliver\AppData\Local\Temp\598eed49-cedc-40e7-b937-5225a477b62c'
    at Object.fs.statSync (fs.js:967:11)
    at Object.exports.walkSync (C:\Users\dnoliver\Git\container-device-conn\node_modules\file\lib\file.js:153:17)
    at DestroyableTransform._flush (C:\Users\dnoliver\Git\container-device-conn\node_modules\gulp-api-doc\index.js:90:5)
    at DestroyableTransform.<anonymous> (C:\Users\dnoliver\Git\container-device-conn\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)
    at prefinish (C:\Users\dnoliver\Git\container-device-conn\node_modules\readable-stream\lib\_stream_writable.js:503:12)
    at finishMaybe (C:\Users\dnoliver\Git\container-device-conn\node_modules\readable-stream\lib\_stream_writable.js:511:7)
    at endWritable (C:\Users\dnoliver\Git\container-device-conn\node_modules\readable-stream\lib\_stream_writable.js:523:3)
    at DestroyableTransform.Writable.end (C:\Users\dnoliver\Git\container-device-conn\node_modules\readable-stream\lib\_stream_writable.js:493:41)
    at DestroyableTransform.onend (C:\Users\dnoliver\Git\container-device-conn\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:188:7)
    at C:\Users\dnoliver\Git\container-device-conn\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
```

**Comment by SamVerschueren** [comment]
Thanks! Should be fixed in `2.1.0`.

Mmm, should've released as `2.0.1`, my bad :).

**Comment by dnoliver** [comment]
hey! thanks @SamVerschueren! 

So, should I use 2.1.0? or wait for 2.0.1?

**Comment by SamVerschueren** [comment]
Can't go back now so just use 2.1.0. Let me know if there are still issues.
